/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupPageImport } from './routes/SignupPage'
import { Route as LoginPageImport } from './routes/LoginPage'
import { Route as EventsImport } from './routes/Events'
import { Route as DashboardImport } from './routes/Dashboard'
import { Route as CreateEventImport } from './routes/CreateEvent'

// Create/Update Routes

const SignupPageRoute = SignupPageImport.update({
  path: '/SignupPage',
  getParentRoute: () => rootRoute,
} as any)

const LoginPageRoute = LoginPageImport.update({
  path: '/LoginPage',
  getParentRoute: () => rootRoute,
} as any)

const EventsRoute = EventsImport.update({
  path: '/Events',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/Dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CreateEventRoute = CreateEventImport.update({
  path: '/CreateEvent',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/CreateEvent': {
      preLoaderRoute: typeof CreateEventImport
      parentRoute: typeof rootRoute
    }
    '/Dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/Events': {
      preLoaderRoute: typeof EventsImport
      parentRoute: typeof rootRoute
    }
    '/LoginPage': {
      preLoaderRoute: typeof LoginPageImport
      parentRoute: typeof rootRoute
    }
    '/SignupPage': {
      preLoaderRoute: typeof SignupPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  CreateEventRoute,
  DashboardRoute,
  EventsRoute,
  LoginPageRoute,
  SignupPageRoute,
])

/* prettier-ignore-end */
